### ISSUE TITLE
申请加入 deepin-riscv64 SIG

### ISSUE THREAD

**Issue by jaxvanyang** [deepin-community/sig-deepin-riscv64#19]
目前在做一些 RISC-V 相关的工作，成功构建过 RISC-V 版本的 Firefox，想测试一下 deepin 的 RISC-V 生态。

**Comment by Zeno-sole** [comment]
@JaxVanYang  请先加入我们的TG群或者matrix 频道交流

**Comment by Zeno-sole** [comment]
matrix 地址 https://matrix.to/#/#deepin-risc-v:matrix.org
