### ISSUE TITLE
您好，我想加入

### ISSUE THREAD

**Issue by changliuxy** [deepin-community/sig-deepin-riscv64#3]
您好，我想加入这个小组，向各位前辈学习，并尽力做出一些贡献

**Comment by Zeno-sole** [comment]
很抱歉这么就才回复，加入小组需要有一定的基础支持，请问您是否有相关的了解

**Comment by changliuxy** [comment]
请问是什么样的基础呢

**Comment by Zeno-sole** [comment]
1.对risc-v架构有基本了解

2.了解debian打包规则

3.熟系Makefile cmake等构建工具的使用方法

**Comment by changliuxy** [comment]
您好，我对risc-v架构和debian打包规则略有了解，Makefile和cmake工具也略有了解但不熟悉可以吗
- 了解过risc-v
- 打包过一些debian包（不复杂的）
- 了解Makefile和cmake
这样的可以做一些简单工作吗

**Comment by tsic404** [comment]
已邀请
